version: '3.7'

services:

  sample:
    image: mcw-gui
    container_name: mcw-gui
    restart: always
    build: ./
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    external:
      name: my-network-pi